services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5001:5001"
